### ISSUE TITLE
404 when downloading hyperwords

### ISSUE THREAD

**Issue by drvenabili** [Garrafao/TemporalReferencing#4]
Hi,

For now, `scripts/get_packs.sh` fails because hyperwords has disappeared from bitbucket. Perhaps it should be changed with this fork? https://github.com/lukaselmer/hyperwords

https://github.com/Garrafao/TemporalReferencing/blob/4847581100748b78426f85f0a5d46ee8f133e06e/scripts/get_packs.sh#L15

**Comment by Garrafao** [comment]
I updated the link. Could you check if it works for you?

**Comment by drvenabili** [comment]
I have also updated the link for word2vecf, which was also from bitbucket: https://github.com/Garrafao/TemporalReferencing/commit/be48c6e4934ba013af5abbf19283a2382ba8b0e8

The current pipeline works as it should.

**Comment by Garrafao** [comment]
thanks!
